### ISSUE TITLE
Automate altering specialist-document schema details and examples

### ISSUE THREAD

**Issue by robmckinnon** [alphagov/govuk-content-schemas#285]
A suggested feature improvement for this process would be to somehow automate altering the schema details and examples. Perhaps triggered by changes to the `specialist-publisher` repo.

At present it's a manually intensive process to add or alter a specialist-document, but mostly following mechanical steps.

An automated mechanism to ensure these files stay in sync with the schema in specialist-publisher would also save time and effort.

**Comment by tijmenb** [comment]
Good idea. We're rebuilding specialist-publisher, so perhaps this could be part of that. cc @tuzz
